on:
  push:
    tags: '*'

jobs:
  bump-homebrew-formula:
    runs-on: macos-latest
    steps:
      - name: Homebrew bump formula
        uses: dawidd6/action-homebrew-bump-formula@v3.10.1
        with:
          token: ${{ secrets.TOKEN }}
          no_fork: false
          tap: davmac314/dinit
          formula: dinit
